name: "DAST OWASP ZAP"

on:
  push:
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP Baseline Scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run ZAP Baseline Scan
        run: |
          docker run --user root -v ${{ github.workspace }}:/zap/wrk/:rw --network=host -t owasp/zap2docker-stable:latest zap-baseline.py -t https://www.zaproxy.org/ -J report_json.json -w report_md.md -r report_html.html -a -c .zap/rules.tsv

      - name: Upload ZAP Scan Reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
