name: "DAST OWASP ZAP"

on:
  push:
  pull_request:

permissions:
  issues: write
  contents: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      # Step 1: Checkout the Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 3: Start the App
      - name: Start App
        run: npm start &
      
      # Optional: Expose App Using ngrok
      - name: Start ngrok
        run: ngrok http 3000 &
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_TOKEN }}

      # Step 4: Perform ZAP Scan
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          # Replace with localhost or ngrok URL
          target: 'http://localhost:3000' 
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Upload ZAP Scan Report
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: owasp-zap-report.html
