name: DevSecOps Pipeline

on:
  push:
    branches:
      - master

permissions:
  contents: write
  security-events: write

jobs:
  build:
    name: Build and Deploy Juice Shop
    runs-on: ubuntu-latest

  security_testing:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      # SAST: CodeQL Security Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
          output: "sast-results"

      # SCA: Snyk Vulnerability Scanning
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
        with:
          command: snyk test --json > sca-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # DAST: OWASP ZAP Dynamic Analysis
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with: 
          target: 'https://demo.owasp-juice.shop'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j -J dast-results.json'
          fail_action: 'false'
          allow_issue_writing: true

      - name: Archive ZAP Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-results
          path: |
            zap-results.json
            *.html
            
      # Upload Scan Results
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-results
          path: |
            sca-results.json

 
