name: "Security and Quality Scans"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  security-events: write

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # SonarCloud token stored as GitHub Secret

jobs:
  # Security Testing Job
  security_testing:
    name: Security Testing (SCA with Snyk, SAST with CodeQL, DAST with OWASP ZAP, Container Security Scan with Trivy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 1: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 2: SCA with Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
        with:
          command: snyk test --json-file-output=snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Step 3: SAST with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript-typescript'
          queries: security-extended
          config: |
            paths-ignore:
              - 'data/static/codefixes'

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          output: codeql-analysis-result.json

      # Step 4: DAST with OWASP ZAP
      - name: Start App
        run: npm start &

      - name: Start ngrok
        run: ngrok http 3000 & 
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_TOKEN }}

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: owasp-zap-report.html

      # Step 5: Container Security Scan with Trivy
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:latest'
          format: 'json'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-report.json'

      # Step 6: Combine all JSON scan results into one file
      - name: Combine Scan Results into One JSON
        run: |
          # Initialize the combined JSON file
          echo '{}' > combined-scan-results.json

          # Append Snyk results to combined JSON
          jq '.snyk = input' snyk-results.json <(cat combined-scan-results.json) > tmp.json && mv tmp.json combined-scan-results.json

          # Append CodeQL results to combined JSON
          jq '.codeql = input' codeql-analysis-result.json <(cat combined-scan-results.json) > tmp.json && mv tmp.json combined-scan-results.json

          # Append ZAP results to combined JSON
          jq '.zap = input' owasp-zap-report.html <(cat combined-scan-results.json) > tmp.json && mv tmp.json combined-scan-results.json

          # Append Trivy results to combined JSON
          jq '.trivy = input' trivy-report.json <(cat combined-scan-results.json) > tmp.json && mv tmp.json combined-scan-results.json

      # Step 7: Upload Combined Scan Results as Artifact
      - name: Upload Combined Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: combined-scan-results
          path: combined-scan-results.json

  # Upload artifacts to SonarCloud (Code Quality)
  sonarcloud_upload:
    runs-on: ubuntu-latest
    name: Code Analysis with SonarCloud

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java (with distribution fix)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Run SonarCloud Scan
      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          # Your SonarCloud project information
          projectBaseDir: "."
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Step 4: Upload SonarCloud Analysis Report (Optional)
      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: ".scannerwork/report-task.txt"
